# Generated by Django 6.0.8 on 2026-09-05 03:39

from django.db import migrations, models


def seed_limits(apps, schema_editor):
    apps.get_model("core", "AttachmentSettings").objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_therapistcomment_patient_read_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('file_limit_mib', models.PositiveIntegerField(default=100)),
                ('card_limit_mib', models.PositiveIntegerField(default=500)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='attachment_settings_singleton'), models.CheckConstraint(condition=models.Q(('card_limit_mib__gte', models.F('file_limit_mib')), ('file_limit_mib__gt', 0)), name='attachment_limits_valid')],
            },
        ),
        migrations.RunPython(seed_limits, migrations.RunPython.noop),
    ]
